general.live_config_reload = true

[window]
opacity = 0.9
dimensions = { columns = 64, lines = 80 }
position = { x = 0, y = 0 }
decorations = "None"

[font]
normal = { family = "JetBrains Mono" }
size = 12
